/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "CreateAuthChallenge": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DefineAuthChallenge": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ExportBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "FnDELETE_admin_dojos_dojoId_locations_locationId": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnDELETE_admin_dojos_dojoId_members_userId": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnDELETE_admin_events_eventId": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnDELETE_admin_events_eventId_ateliers_id": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnDELETE_admin_events_eventId_registrations_registrationId_checkin": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnDELETE_events_eventId_volunteers_me": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnDELETE_registrations_registrationId": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnGET_admin_ateliers": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnGET_admin_dojos_dojoId_events": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnGET_admin_dojos_dojoId_members": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnGET_admin_events_eventId_registrations": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnGET_admin_events_eventId_registrations_export": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnGET_admin_events_eventId_volunteers": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnGET_admin_events_eventId_waitlist": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnGET_auth_session": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnGET_dojos": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnGET_dojos_dojoId": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnGET_dojos_dojoId_events": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnGET_events": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnGET_events_eventId": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnGET_users_me": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnGET_users_me_memberships": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnGET_users_me_registrations": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnPATCH_admin_events_eventId_registrations_registrationId_checkin": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnPATCH_admin_events_eventId_volunteers_userId_checkin": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnPOST_admin_dojos": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnPOST_admin_dojos_dojoId_events": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnPOST_admin_dojos_dojoId_locations": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnPOST_admin_dojos_dojoId_members_add": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnPOST_admin_events_eventId_ateliers": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnPOST_admin_events_eventId_waitlist_id_promote": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnPOST_admin_users_userId_role": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnPOST_auth_logout": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnPOST_events_eventId_registrations": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnPOST_events_eventId_volunteers": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnPUT_admin_dojos_dojoId": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnPUT_admin_dojos_dojoId_locations_locationId": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnPUT_admin_dojos_dojoId_members_userId_role": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnPUT_admin_dojos_dojoId_waitlist-mode": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnPUT_admin_events_eventId": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnPUT_admin_registrations_registrationId": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FnPUT_users_me": {
      "name": string
      "type": "sst.aws.Function"
    }
    "MainTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "PostConfirmation": {
      "name": string
      "type": "sst.aws.Function"
    }
    "PreSignUp": {
      "name": string
      "type": "sst.aws.Function"
    }
    "PreTokenGeneration": {
      "name": string
      "type": "sst.aws.Function"
    }
    "VerifyAuthChallenge": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Web": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}

import "sst"
export {}